---@diagnostic disable: undefined-global

			-- ============ DO NOT DO ANYTHING BELOW! ============ --

local mod = get_mod("Enhanced_descriptions")
local InputUtils = require("scripts/managers/input/input_utils")
local iu_actit = InputUtils.apply_color_to_input_text

--[+ ++NUMBERS++ +]--
	--[+ +Variables+ +]--
	local var_col = Color[mod:get("variables_text_colour")](255, true)
	-- local m_tghn_reg_del_rgb = iu_actit("-{toughness_regen_delay_multiplier:%s}", var_col) ????????
		--[+ Blessings +]--
	local ammo_var_rgb = iu_actit("{ammo:%s}", var_col)
	local attack_spd_var_rgb = iu_actit("{attack_speed:%s}", var_col)
	local amount_var_rgb = iu_actit("{amount}", var_col)						-- +Penances
	local amountp_var_rgb = iu_actit("{amount:%s}", var_col)
	local block_var_rgb = iu_actit("{block_cost:%s}", var_col)
	local blltam_var_rgb = iu_actit("{bullet_amount:%s}", var_col)
	local buildup_var_rgb = iu_actit("{buildup_amount:%s}", var_col)
	local chnc_var_rgb = iu_actit("{chance:%s}", var_col)
	local chrgtime_var_rgb = iu_actit("{charge_time:%s}", var_col)
	local cleave_var_rgb = iu_actit("{cleave:%s}", var_col)
	local dmgcls_var_rgb = iu_actit("{close_damage:%s}", var_col)
	local cd_var_rgb = iu_actit("{cooldown:%s}", var_col)
	local cd_dur_var_rgb = iu_actit("{cooldown_duration:%s}", var_col)
	local countd_var_rgb = iu_actit("{count:%d}", var_col)
	local counts_var_rgb = iu_actit("{count:%s}", var_col)
	local crit_var_rgb = iu_actit("{crit_chance:%s}", var_col)
	local critdmg_var_rgb = iu_actit("{crit_damage:%s}", var_col)
	local critwkspdmg_var_rgb = iu_actit("{crit_weakspot_damage:%s}", var_col)
	local critchmax_var_rgb = iu_actit("{crit_chance_max:%s}", var_col)
	local critchmin_var_rgb = iu_actit("{crit_chance_min:%s}", var_col)
	local dmg_var_rgb = iu_actit("{damage:%s}", var_col)
	local dmgnr_var_rgb = iu_actit("{damage_near:%s}", var_col)
	local dmgvsprsd_var_rgb = iu_actit("{damage_vs_suppressed}", var_col)
	local dmgvsstgr_var_rgb = iu_actit("{vs_stagger:%s}", var_col)
	local dmgvogrmon_var_rgb = iu_actit("{dmg_vs_ogryn_monster:%s}", var_col)
	local dist_rgb = iu_actit("{distance}", var_col)							-- +Penances
	local dur_var_rgb = iu_actit("{duration:%s}", var_col)
	local explosion_rad_var_rgb = iu_actit("{explosion_radius:%s}", var_col)
	local fin_var_rgb = iu_actit("{finesse:%s}", var_col)
	local health_pc_rgb = iu_actit("{health}%", var_col)						-- !Penances
	local heat_diss_var_rgb = iu_actit("{heat_dissipation:%s}", var_col)
	local heat_pc_var_rgb = iu_actit("{heat_percentage:%s}", var_col)
	local heat_red_var_rgb = iu_actit("{heat_reduction:%s}", var_col)
	local dmghvy_var_rgb = iu_actit("{heavy_damage:%s}", var_col)
	local hit_var_rgb = iu_actit("{hit:%s}", var_col)
	local hitmass_var_rgb = iu_actit("{hit_mass:%s}", var_col)
	local hit_mass_red_var_rgb = iu_actit("{hit_mass_reduction:%s}", var_col)
	local impact_var_rgb = iu_actit("{impact:%s}", var_col)
	local impmod_var_rgb = iu_actit("{impact_modifier:%s}", var_col)
	local interval_var_rgb = iu_actit("{interval:%s}", var_col)
	local maxstks_var_rgb = iu_actit("{max_stacks:%s}", var_col)
	local max_stk_cnt_var_rgb = iu_actit("{max_stack_count:%s}", var_col)
	local mel_weapsp_dmg_var_rgb = iu_actit("{melee_weakspot_damage}", var_col)
	local min_stk_cnt_var_rgb = iu_actit("{min_stack_count:%s}", var_col)
	local movspd_var_rgb = iu_actit("{movement_speed:%s}", var_col)
	local mult_hit_var_rgb = iu_actit("{multiple_hit:%s}", var_col)
	local num_enemies_rgb = iu_actit("{num_enemies}", var_col)					-- !Penances
	local overheat_red_var_rgb = iu_actit("{overheat_reduction:%s}", var_col)
	local pwr_var_rgb = iu_actit("{power:%s}", var_col)
	local pwrlvl_var_rgb = iu_actit("{power_level:%s}", var_col)
	local procch_var_rgb = iu_actit("{proc_chance:%s}", var_col)
	local radius_var_rgb = iu_actit("{radius:%s}", var_col)
	local rangcrtdmg_var_rgb = iu_actit("{ranged_crit_damage:%s}", var_col)
	local range_var_rgb = iu_actit("{range:%s}", var_col)
	local rbc_rgb = iu_actit("{reduced_block_cost:%s}", var_col)
	local recoil_red_var_rgb = iu_actit("{recoil_reduction:%s}", var_col)
	local red_var_rgb = iu_actit("{reduction:%s}", var_col)
	local reload_var_rgb = iu_actit("{reload_speed:%s}", var_col)
	local rend_var_rgb = iu_actit("{rend:%s}", var_col)
	local rending_var_rgb = iu_actit("{rending:%s}", var_col)
	local rending_pc_var_rgb = iu_actit("{rending_percentage:%s}", var_col)
	local stacks_num_var_rgb = iu_actit("{num_stacks:%s}", var_col)
	local stacks_var_rgb = iu_actit("{stacks:%s}", var_col)
	local stam_var_rgb = iu_actit("{stamina:%s}", var_col)
	local stgr_var_rgb = iu_actit("{stagger:%s}", var_col)
	local spprsn_var_rgb = iu_actit("{suppression:%s}", var_col)
	local stgrrang_var_rgb = iu_actit("{ranged_stagger:%s}", var_col)
	local stgrrdct_var_rgb = iu_actit("{stagger_reduction:%s}", var_col)
	local target_rgb = iu_actit("{target}", var_col)					-- +Talents +Penances
	local tghns_var_rgb = iu_actit("{toughness:%s}", var_col)
	local time_rgb = iu_actit("{time}", var_col)								-- !Penances
	local time_var_rgb = iu_actit("{time:%s}", var_col)
	local time_wind_rgb = iu_actit("{time_window}", var_col)					-- !Penances
	local value_var_rgb = iu_actit("{value:%s}", var_col)
	local warpchrg_var_rgb = iu_actit("{warp_charge:%s}", var_col)
	local wkspdmg_var_rgb = iu_actit("{weakspot_damage:%s}", var_col)
	local weapsprd_var_rgb = iu_actit("{weapon_spread:%s}", var_col)
		--[+ Plus +]--
	local p_chrgspd_var_rgb = iu_actit("+{charge_speed:%s}", var_col)
	local p_xtrahits_var_rgb = iu_actit("+{extra_hits:%s}", var_col)
	local p_stacks_var_rgb = iu_actit("+{stacks:%s}", var_col)

	--[+ Curios +]--
	local abil_cd_rgb = iu_actit("{ability_cooldown_modifier:%s}", var_col)
	local blckcst_rgb = iu_actit("{block_cost_multiplier:%s}", var_col)
	local corr_rgb = iu_actit("{corruption_taken_multiplier:%s}", var_col)
	local corrgrm_rgb = iu_actit("{permanent_damage_converter_resistance:%s}", var_col)
	local credits_rgb = iu_actit("{mission_reward_credit_modifier:%s}", var_col)
	local dmg_red_rgb = iu_actit("{damage_reduction:%s}", var_col)
	local gears_rgb = iu_actit("{mission_reward_gear_instead_of_weapon_modifier:%s}", var_col)
	local maxhlth_rgb = iu_actit("{max_health_modifier:%s}", var_col)
	local maxstam_rgb = iu_actit("{stamina_modifier:%s}", var_col)
	local maxtghns_rgb = iu_actit("{toughness_bonus:%s}", var_col)
	local maxwnds_rgb = iu_actit("{extra_max_amount_of_wounds:%s}", var_col)
	local revive_rgb = iu_actit("{revive_speed_modifier:%s}", var_col)
	local stamreg_rgb = iu_actit("{stamina_regeneration_modifier:%s}", var_col)
	local tghn_reg_del_rgb = iu_actit("{toughness_regen_delay_multiplier:%s}", var_col)
	local xp_rgb = iu_actit("{mission_reward_xp_modifier:%s}", var_col)
	local bcm_rgb = iu_actit("{sprinting_cost_multiplier:%s}", var_col)

		--[+ Numbers +]--
	local n_minus_rgb = iu_actit("-", var_col)
	local n_plus_rgb = iu_actit("+", var_col)
	local n_meter_rgb = iu_actit("m", var_col) -- meter
	local n_second_rgb = iu_actit("s", var_col) -- second
	local n_0_rgb = iu_actit("0", var_col)
	local n_01_rgb = iu_actit("0.1", var_col)
	local n_033_rgb = iu_actit("0.33", var_col)
	local n_055_rgb = iu_actit("0.55", var_col)
	local n_0875_rgb = iu_actit("0.55", var_col)
	local n_075_rgb = iu_actit("0.75", var_col)
	local n_1_rgb = iu_actit("1", var_col)
	local n_1_5_rgb = iu_actit("1.5", var_col)
	local n_1_7_rgb = iu_actit("1.7", var_col)
	local n_2_rgb = iu_actit("2", var_col)
	local n_2e_rgb = iu_actit("2e", var_col)
	local n_2_5_rgb = iu_actit("2.5", var_col)
	local n_3_rgb = iu_actit("3", var_col)
	local n_3e_rgb = iu_actit("3e", var_col)
	local n_3_5_rgb = iu_actit("3.5", var_col)
	local n_3_75_rgb = iu_actit("3.75", var_col)
	local n_4_rgb = iu_actit("4", var_col)
	local n_4e_rgb = iu_actit("4e", var_col)
	local n_5_rgb = iu_actit("5", var_col)
	local n_6_rgb = iu_actit("6", var_col)
	local n_6_03_rgb = iu_actit("6.03", var_col)
	local n_7_rgb = iu_actit("7", var_col)
	local n_8_rgb = iu_actit("8", var_col)
	local n_9_rgb = iu_actit("9", var_col)
	local n_10_rgb = iu_actit("10", var_col)
	local n_10_5_rgb = iu_actit("10.5", var_col)
	local n_12_rgb = iu_actit("12", var_col)
	local n_12_5_rgb = iu_actit("12.5", var_col)
	local n_15_rgb = iu_actit("15", var_col)
	local n_16_rgb = iu_actit("16", var_col)
	local n_20_rgb = iu_actit("20", var_col)
	local n_21_rgb = iu_actit("21", var_col)
	local n_25_rgb = iu_actit("25", var_col)
	local n_30_rgb = iu_actit("30", var_col)
	local n_37_5_rgb = iu_actit("37.5", var_col)
	local n_40_rgb = iu_actit("40", var_col)
	local n_45_rgb = iu_actit("45", var_col)
	local n_50_rgb = iu_actit("50", var_col)
	local n_59_85_rgb = iu_actit("59.85", var_col)
	local n_64_rgb = iu_actit("64", var_col)
	local n_200_rgb = iu_actit("200", var_col)
	local n_225_rgb = iu_actit("225", var_col)
	local n_340_rgb = iu_actit("340", var_col)
	local n_380_rgb = iu_actit("380", var_col)
	local n_585_rgb = iu_actit("585", var_col)
		--[+ Percentages +]--
	local pc_rgb = iu_actit("%", var_col)
	local pc_2_rgb = iu_actit("2%", var_col)
	local pc_2_5_rgb = iu_actit("2.5%", var_col)
	local pc_1_rgb = iu_actit("1%", var_col)
	local pc_4_rgb = iu_actit("4%", var_col)
	local pc_5_rgb = iu_actit("5%", var_col)
	local pc_6_rgb = iu_actit("6%", var_col)
	local pc_8_rgb = iu_actit("8%", var_col)
	local pc_8_5_rgb = iu_actit("8.5%", var_col)
	local pc_10_rgb = iu_actit("10%", var_col)
	local pc_11_rgb = iu_actit("11%", var_col)
	local pc_12_rgb = iu_actit("12%", var_col)
	local pc_15_rgb = iu_actit("15%", var_col)
	local pc_20_rgb = iu_actit("20%", var_col)
	local pc_25_rgb = iu_actit("25%", var_col)
	local pc_32_rgb = iu_actit("32%", var_col)
	local pc_33_rgb = iu_actit("33%", var_col)
	local pc_40_rgb = iu_actit("40%", var_col)
	local pc_48_rgb = iu_actit("48%", var_col)
	local pc_50_rgb = iu_actit("50%", var_col)
	local pc_97_rgb = iu_actit("97%", var_col)
	local pc_100_rgb = iu_actit("100%", var_col)
	local pc_p10_rgb = iu_actit("+10%", var_col)
	local pc_p12_rgb = iu_actit("+12%", var_col)
	local pc_p19_rgb = iu_actit("+19%", var_col)

	-- m_tghn_reg_del_rgb = m_tghn_reg_del_rgb,

return {
	abil_cd_rgb = abil_cd_rgb,
	ammo_var_rgb = ammo_var_rgb,
	amount_var_rgb = amount_var_rgb,
	amountp_var_rgb = amountp_var_rgb,
	attack_spd_var_rgb = attack_spd_var_rgb,
	bcm_rgb = bcm_rgb,
	blckcst_rgb = blckcst_rgb,
	block_var_rgb = block_var_rgb,
	blltam_var_rgb = blltam_var_rgb,
	buildup_var_rgb = buildup_var_rgb,
	chnc_var_rgb = chnc_var_rgb,
	chrgtime_var_rgb = chrgtime_var_rgb,
	cd_dur_var_rgb = cd_dur_var_rgb,
	cd_var_rgb = cd_var_rgb,
	corr_rgb = corr_rgb,
	corrgrm_rgb = corrgrm_rgb,
	countd_var_rgb = countd_var_rgb,
	counts_var_rgb = counts_var_rgb,
	cleave_var_rgb = cleave_var_rgb,
	credits_rgb = credits_rgb,
	crit_var_rgb = crit_var_rgb,
	critchmax_var_rgb = critchmax_var_rgb,
	critchmin_var_rgb = critchmin_var_rgb,
	critdmg_var_rgb = critdmg_var_rgb,
	critwkspdmg_var_rgb = critwkspdmg_var_rgb,
	dist_rgb = dist_rgb,
	dmg_var_rgb = dmg_var_rgb,
	dmg_red_rgb = dmg_red_rgb,
	dmgcls_var_rgb = dmgcls_var_rgb,
	dmghvy_var_rgb = dmghvy_var_rgb,
	dmgnr_var_rgb = dmgnr_var_rgb,
	dmgvogrmon_var_rgb = dmgvogrmon_var_rgb,
	dmgvsprsd_var_rgb = dmgvsprsd_var_rgb,
	dmgvsstgr_var_rgb = dmgvsstgr_var_rgb,
	dur_var_rgb = dur_var_rgb,
	explosion_rad_var_rgb = explosion_rad_var_rgb,
	fin_var_rgb = fin_var_rgb,
	gears_rgb = gears_rgb,
	health_pc_rgb = health_pc_rgb,
	heat_diss_var_rgb = heat_diss_var_rgb,
	heat_red_var_rgb = heat_red_var_rgb,
	heat_pc_var_rgb = heat_pc_var_rgb,
	hit_var_rgb = hit_var_rgb,
	hit_mass_red_var_rgb = hit_mass_red_var_rgb,
	hitmass_var_rgb = hitmass_var_rgb,
	impact_var_rgb = impact_var_rgb,
	impmod_var_rgb = impmod_var_rgb,
	interval_var_rgb = interval_var_rgb,
	maxstks_var_rgb = maxstks_var_rgb,
	max_stk_cnt_var_rgb = max_stk_cnt_var_rgb,
	maxhlth_rgb = maxhlth_rgb,
	maxstam_rgb = maxstam_rgb,
	maxtghns_rgb = maxtghns_rgb,
	maxwnds_rgb = maxwnds_rgb,
	mel_weapsp_dmg_var_rgb = mel_weapsp_dmg_var_rgb,
	min_stk_cnt_var_rgb = min_stk_cnt_var_rgb,
	movspd_var_rgb = movspd_var_rgb,
	mult_hit_var_rgb = mult_hit_var_rgb,
	num_enemies_rgb = num_enemies_rgb,
	overheat_red_var_rgb = overheat_red_var_rgb,
	procch_var_rgb = procch_var_rgb,
	pwr_var_rgb = pwr_var_rgb,
	pwrlvl_var_rgb = pwrlvl_var_rgb,
	radius_var_rgb = radius_var_rgb,
	rangcrtdmg_var_rgb = rangcrtdmg_var_rgb,
	range_var_rgb = range_var_rgb,
	rbc_rgb = rbc_rgb,
	recoil_red_var_rgb = recoil_red_var_rgb,
	red_var_rgb = red_var_rgb,
	reload_var_rgb = reload_var_rgb,
	rend_var_rgb = rend_var_rgb,
	rending_pc_var_rgb = rending_pc_var_rgb,
	rending_var_rgb = rending_var_rgb,
	revive_rgb = revive_rgb,
	spprsn_var_rgb = spprsn_var_rgb,
	stacks_var_rgb = stacks_var_rgb,
	stacks_num_var_rgb = stacks_num_var_rgb,
	stam_var_rgb = stam_var_rgb,
	stamreg_rgb = stamreg_rgb,
	stgr_var_rgb = stgr_var_rgb,
	stgrrang_var_rgb = stgrrang_var_rgb,
	stgrrdct_var_rgb = stgrrdct_var_rgb,
	target_rgb = target_rgb,
	tghn_reg_del_rgb = tghn_reg_del_rgb,
	tghns_var_rgb = tghns_var_rgb,
	time_rgb = time_rgb,
	time_var_rgb = time_var_rgb,
	time_wind_rgb = time_wind_rgb,
	value_var_rgb = value_var_rgb,
	warpchrg_var_rgb = warpchrg_var_rgb,
	weapsprd_var_rgb = weapsprd_var_rgb,
	wkspdmg_var_rgb = wkspdmg_var_rgb,
	xp_rgb = xp_rgb,

	p_chrgspd_var_rgb = p_chrgspd_var_rgb,
	p_xtrahits_var_rgb = p_xtrahits_var_rgb,
	p_stacks_var_rgb = p_stacks_var_rgb,

	n_plus_rgb = n_plus_rgb,
	n_meter_rgb = n_meter_rgb,
	n_second_rgb = n_second_rgb,
	n_minus_rgb = n_minus_rgb,
	n_0_rgb = n_0_rgb,
	n_01_rgb = n_01_rgb,
	n_033_rgb = n_033_rgb,
	n_055_rgb = n_055_rgb,
	n_0875_rgb = n_0875_rgb,
	n_075_rgb = n_075_rgb,
	n_1_rgb = n_1_rgb,
	n_1_5_rgb = n_1_5_rgb,
	n_1_7_rgb = n_1_7_rgb,
	n_2_rgb = n_2_rgb,
	n_2e_rgb = n_2e_rgb,
	n_2_5_rgb = n_2_5_rgb,
	n_3_rgb = n_3_rgb,
	n_3e_rgb = n_3e_rgb,
	n_3_5_rgb = n_3_5_rgb,
	n_3_75_rgb = n_3_75_rgb,
	n_4_rgb = n_4_rgb,
	n_4e_rgb = n_4e_rgb,
	n_5_rgb = n_5_rgb,
	n_6_rgb = n_6_rgb,
	n_6_03_rgb = n_6_03_rgb,
	n_7_rgb = n_7_rgb,
	n_8_rgb = n_8_rgb,
	n_9_rgb = n_9_rgb,
	n_10_rgb = n_10_rgb,
	n_10_5_rgb = n_10_5_rgb,
	n_12_rgb = n_12_rgb,
	n_12_5_rgb = n_12_5_rgb,
	n_15_rgb = n_15_rgb,
	n_16_rgb = n_16_rgb,
	n_20_rgb = n_20_rgb,
	n_21_rgb = n_21_rgb,
	n_25_rgb = n_25_rgb,
	n_30_rgb = n_30_rgb,
	n_37_5_rgb = n_37_5_rgb,
	n_40_rgb = n_40_rgb,
	n_45_rgb = n_45_rgb,
	n_50_rgb = n_50_rgb,
	n_59_85_rgb = n_59_85_rgb,
	n_64_rgb = n_64_rgb,
	n_200_rgb = n_200_rgb,
	n_225_rgb = n_225_rgb,
	n_340_rgb = n_340_rgb,
	n_380_rgb = n_380_rgb,
	n_585_rgb = n_585_rgb,

	pc_rgb = pc_rgb,
	pc_1_rgb = pc_1_rgb,
	pc_2_rgb = pc_2_rgb,
	pc_2_5_rgb = pc_2_5_rgb,
	pc_4_rgb = pc_4_rgb,
	pc_5_rgb = pc_5_rgb,
	pc_6_rgb = pc_6_rgb,
	pc_8_rgb = pc_8_rgb,
	pc_8_5_rgb = pc_8_5_rgb,
	pc_10_rgb = pc_10_rgb,
	pc_11_rgb = pc_11_rgb,
	pc_12_rgb = pc_12_rgb,
	pc_15_rgb = pc_15_rgb,
	pc_20_rgb = pc_20_rgb,
	pc_25_rgb = pc_25_rgb,
	pc_32_rgb = pc_32_rgb,
	pc_33_rgb = pc_33_rgb,
	pc_40_rgb = pc_40_rgb,
	pc_48_rgb = pc_48_rgb,
	pc_50_rgb = pc_50_rgb,
	pc_97_rgb = pc_97_rgb,
	pc_100_rgb = pc_100_rgb,
	pc_p10_rgb = pc_p10_rgb,
	pc_p12_rgb = pc_p12_rgb,
	pc_p19_rgb = pc_p19_rgb,

}
