---@diagnostic disable: undefined-global, undefined-field
-- Version 4.0

local mod = get_mod("Enhanced_descriptions")
local InputUtils = require("scripts/managers/input/input_utils")

-- LOCALIZATION CONFIGURATION
local LOCALIZATION_GROUPS = {
	-- Main modules
	"enable_menus_file",
	"enable_curious_file",
	"enable_penances_file",
	"enable_weapons_file",
	"enable_talents_file",
	"enable_names_file",
	"enable_names_tal_bless_file",

	"bleed",
	"brittleness",
	"burn",
	"cleave",
	"coherency",
	"combat_ability",
	"corruption",
	"crit",
	"damage",
	"electrocuted",
	"finesse",
	"health",
	"hit_mass",
	"impact",
	"peril",
	"power",
	"rending",
	"soulblaze",
	"stagger",
	"stamina",
	"toughness",
	"weakspot",

	-- Classes and abilities
	"class_psyker",
	"precision",
	"class_ogryn",
	"fnp",
	"luckyb",
	"trample",
	"class_zealot",
	"fury",
	"momentum",
	"stealth",
	"class_veteran",
	"focus",
	"focust",
	"meleespec",
	"rangedspec",
	"class_arbites",
	-- "meleejust",
	-- "rangedjust",

	-- Misc
	"talents",
	"talents_penances",
	"numbers",
	"variables",
	"note",
	"warning",

	-- Difficulty
	"sedition",
	"uprising",
	"malice",
	"heresy",
	"damnation",
	"auric",
}

-- UTILITY FUNCTIONS
local function readable(text)
	local tokens = string.split(text, "_")
	for i, token in ipairs(tokens) do
		tokens[i] = string.upper(string.sub(token, 1, 1)) .. string.sub(token, 2)
	end
	return table.concat(tokens, " ")
end

local function add_color_localizations(localizations)
	for _, color_name in ipairs(Color.list) do
		local color_values = Color[color_name](255, true)
		local text = InputUtils.apply_color_to_input_text(readable(color_name), color_values)
		localizations[color_name] = { en = text }
	end
end

local function add_localisation_entry(localizations, type_name)
	localizations[type_name .. "_text_colour"] = {
		en = "Pick color",
		fr = "Couleur", 
		ru = "Выберите цвет",
		["zh-tw"] = "顏色",
		["zh-cn"] = "颜色",
-- FOR TRANSLATORS
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-BR"] = "",
		-- es = "",
	}
end

-- MAIN LOCALIZATIONS
local localizations = {
	mod_name = {
		en = "Enhanced Descriptions",
		ru = "Улучшенные описания",
		["zh-tw"] = "描述改善",
		["zh-cn"] = "描述增强",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-BR"] = "",
		-- es = "",
	},
	mod_description = {
		en = "Enhanced Descriptions — fixes and additions to game descriptions. Merged mod. Included TALENTS, CURIOS, WEAPON PERKS and BLESSINGS.",
		fr = "Descriptions avancées : corrections et ajouts aux descriptions du jeu. Version fusionnée incluant les Talents, Curiosités, Atouts et Bénédictions des armes.",
		ru = "Улучшенные описания — Улучшенная локализация и расширенные описания ТАЛАНТОВ, БЛАГОСЛОВЕНИЙ и УЛУЧШЕНИЙ ОРУЖИЯ, а также РЕЛИКВИЙ(диковинок), различных МЕНЮ и всех мест, куда я успел добраться.",
		["zh-tw"] = "描述改善 - 修正和添加遊戲內的各項描述。包括天賦、珍品、武器特性、領主任務和祝福；目前苦修僅支援俄語。",
		["zh-cn"] = "描述增强 - 修正并增加游戏内文本的描述的一体式模组。包含天赋，珍品，武器专长及武器祝福。",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-BR"] = "",
		-- es = "",
	},

	-- Main modules
	enable_weapons_file = {
		en = "Toggle \"Weapons\" module",
		fr = "Activer le module des armes",
		ru = "Модуль «Оружие»",
		["zh-tw"] = "切換 {#color(255, 223,135)}武器{#reset()} 模組",
		["zh-cn"] = "启用「武器」模块",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-BR"] = "",
		-- es = "",
	},
	enable_weapons_file_description = {
		en = "This module highlights the Words and Numbers of Weapon Blessings and Perks. You can disable this module if you don't need it.",
		fr = "Ce module met en évidence les mots et les chiffres des bénédictions et avantages des armes. Vous pouvez désactiver ce module si vous n'en avez pas besoin.",
		ru = "Этот модуль выделяет слова и числа Благословений и Улучшений Оружия. Вы можете отключить этот модуль, если он вам не нужен.",
		["zh-tw"] = "突顯 {#color(255, 223,135)}武器祝福{#reset()} 和 {#color(255, 223,135)}附加屬性{#reset()} 的文字和數字。\n\n如果您不需要此模組，可以將其禁用。",
		["zh-cn"] = "此模块将高亮显示武器的祝福和专长的关键词及数字，并重写了效果描述。\n可以按需开关此模块。",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-BR"] = "",
		-- es = "",
	},

	enable_curious_file = {
		en = "Toggle \"Curios\" module",
		fr = "Activer le module des curiosités",
		ru = "Модуль «Реликвии»",
		["zh-tw"] = "切換 {#color(255, 223,135)}珍品{#reset()} 模組",
		["zh-cn"] = "启用「珍品」模块",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-BR"] = "",
		-- es = "",
	},
	enable_curious_file_description = {
		en = "This module highlights the Words and Numbers of the Blessings and Perks of the Curios. You can disable this module if you don't need it.",
		fr = "Ce module met en évidence les mots et les chiffres des bénédictions et avantages des curiosités. Vous pouvez désactiver ce module si vous n'en avez pas besoin.",
		ru = "Этот модуль выделяет слова и числа Благословений и Улучшений Реликвий. Вы можете отключить этот модуль, если он вам не нужен.",
		["zh-tw"] = "突顯 {#color(255, 223,135)}珍品{#reset()} 的 {#color(255, 223,135)}祝福{#reset()} 和 {#color(255, 223,135)}附加屬性{#reset()} 的文字和數字。\n如果您不需要此模組，可以將其禁用。",
		["zh-cn"] = "此模块将高亮显示珍品的祝福和专长的关键词及数字。\n可以按需开关此模块。",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-BR"] = "",
		-- es = "",
	},

	enable_menus_file = {
		en = "Toggle \"Menus\" module",
		fr = "Activer le module des menus",
		ru = "Модуль «Меню»",
		["zh-tw"] = "切換 {#color(255, 223,135)}領主{#reset()} 模組",
		["zh-cn"] = "启用「菜单」模块",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-BR"] = "",
		-- es = "",
	},
	enable_menus_file_description = {
		en = "This module highlights the Numbers of the Melk's Contracts. You can disable this module if you don't need it.",
		fr = "Ce module met en évidence les numéros des contrats de Melk. Vous pouvez désactiver ce module si vous n'en avez pas besoin.",
		ru = "Этот модуль исправляет надписи в различных меню. Вы можете отключить этот модуль, если он вам не нужен.",
		["zh-tw"] = "突顯領主的 {#color(255, 223,135)}合約{#reset()} 數字。",
		["zh-cn"] = "此模块将高亮梅尔克的协议中的数字，并修正菜单中的部分文字。",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-BR"] = "",
		-- es = "",
	},
	enable_talents_file = {
		en = "Toggle \"Talents\" module",
		fr = "Activer le module des talents",
		ru = "Модуль «Таланты»",
		["zh-tw"] = "切換 {#color(255, 223,135)}天賦{#reset()} 模組",
		["zh-cn"] = "启用「天赋」模块",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-BR"] = "",
		-- es = "",
	},
	enable_talents_file_description = {
		en = "This module highlights Talent words. You can disable this module if you don't need it, but all Extended Descriptions will also be disabled.",
		fr = "Ce module met en avant les mots clés des Talents. Vous pouvez désactiver ce module si vous n'en avez pas besoin mais les descriptions avancées seront également désactiver.",
		ru = "Этот модуль выделяет слова Талантов и немного улучшает описания некоторых из них. Вы можете отключить этот модуль, если он вам не нужен.",
		["zh-tw"] = "突顯 {#color(255, 223,135)}天賦{#reset()} 文字。\n如果您不需要此模組，可以將其禁用，但所有擴充描述也將被禁用。",
		["zh-cn"] = "此模块将高亮天赋的关键词。\n可以按需开关此模块。\n需注意，关闭此模块将同时禁用扩充描述功能。",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-BR"] = "",
		-- es = "",
	},
	enable_penances_file = {
		en = "{#color(15, 15, 15)}(Toggle \"Penances\" module){#reset()}",
		-- fr = "",
		ru = "Модуль «Искупления»",
		["zh-tw"] = "切換 {#color(255, 223,135)}苦修{#reset()} 模組",
		["zh-cn"] = "（启用「苦修」模块）",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-BR"] = "",
		-- es = "",
	},
	enable_penances_file_description = { -- LA DESCRIPTION EN FRANÇAIS DOIT ÊTRE CORRIGÉE !!!
		en = "{#color(255, 35, 5)}BETA! FOR NOW ONLY FOR THE RUSSIAN VERSION!{#reset()} This module highlights the Words and Numbers of the Penances. You can disable this module if you don't need it.",
		-- fr = "Ce module met en évidence les numéros des contrats de Melk. Vous pouvez désactiver ce module si vous n'en avez pas besoin.",
		ru = "Этот модуль выделяет слова Искуплений и немного переписывает некоторые из них. Названия талантов берутся из модуля с исправленными названиями талантов! Вы можете отключить этот модуль, если он вам не нужен.",
		["zh-tw"] = "突顯 {#color(255, 223,135)}苦修{#reset()} 的文字。\n可以按需求開關此模組。",
	["zh-cn"] = "{#color(255, 35, 5)}测试版！仅供俄语版本使用！{#reset()} 此模块将高亮苦修中的数字。",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-BR"] = "",
		-- es = "",
	},

	-- FOR RUSSIAN VERSION ONLY!
	enable_names_file = {
		en = "{#color(15, 15, 15)}(Toggle \"Names of enemies and weapons\" module){#reset()}",
		-- fr = "",
		ru = "Модуль «Названия врагов и оружия»",
		["zh-tw"] = "切換 {#color(255, 223,135)}敵人{#reset()} 與 {#color(255, 223,135)}武器名稱{#reset()} 模組",
		["zh-cn"] = "{#color(15, 15, 15)}(启用「敌人与武器名称」模块){#reset()}",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-BR"] = "",
		-- es = "",
	},
	enable_names_file_description = { -- LA DESCRIPTION EN FRANÇAIS DOIT ÊTRE CORRIGÉE !!!
		en = "{#color(255, 35, 5)}FOR RUSSIAN VERSION ONLY!{#reset()}",
		-- en = "This module changes the names of weapons and enemies. You can disable this module if you don't need it.",
		-- fr = "Ce module met en évidence les numéros des contrats de Melk. Vous pouvez désactiver ce module si vous n'en avez pas besoin.",
		ru = "Этот модуль меняет названия некоторых врагов и видов брони, а также улучшает названия некоторого оружия, моделей и кузниц. Вы можете отключить этот модуль, если он вам не нужен.",
		["zh-tw"] = "突顯 {#color(255, 223,135)}武器型號{#reset()} 。可以按需求開關此模組。\n{#color(255, 155, 55)}但你必須按下 CTRL+SHIFT+R 以重載模組！{#reset()}\n{#color(100, 100, 100)} \n\n要切換此功能，需要重啟遊戲或進入 Darktide Mod Framework 選項並啟用開發人員模式。{#reset()}",
		["zh-cn"] = "{#color(255, 35, 5)}仅供俄语版本使用！{#reset()}此模块将高亮敌人与武器名称。",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-BR"] = "",
		-- es = "",
	},
	enable_names_tal_bless_file = {
		en = "{#color(15, 15, 15)}(Toggle \"Names of Talents and Blessings\" module){#reset()}",
		-- fr = "",
		ru = "Модуль «Названия талантов и благословений»",
		["zh-tw"] = "{#color(15, 15, 15)}(切換『天賦與祝福名稱』模組){#reset()}",
		["zh-cn"] = "{#color(15, 15, 15)}(启用「天赋与祝福名称」模块){#reset()}",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-BR"] = "",
		-- es = "",
	},
	enable_names_tal_bless_file_description = {	-- LA DESCRIPTION EN FRANÇAIS DOIT ÊTRE CORRIGÉE !!!
		en = "{#color(255, 35, 5)}FOR RUSSIAN VERSION ONLY!{#reset()}",
		-- en = "This module changes the names of Talents and Blessings. You can disable this module if you don't need it.",
		-- fr = "Ce module met en évidence les numéros des contrats de Melk. Vous pouvez désactiver ce module si vous n'en avez pas besoin.",
		ru = "Этот модуль меняет названия некоторых Талантов и Благословений. Вы можете конечно отключить этот модуль, но тогда названия талантов в Расширенных описаниях и в Искуплениях не будут совпадать. Более правильный перевод, но может немного ухудшать понимание вами других игроков и другими игроками вас, т.к. будет чуть сложнее соотносить названия.",
		["zh-tw"] = "{#color(255, 35, 5)}測試版！僅供俄語版本使用！\n{#reset()}突顯 {#color(255, 223,135)}天賦{#reset()} 與 {#color(255, 223,135)}祝福{#reset()} 名稱。\n可以按需求開關此模組。",
		["zh-cn"] = "{#color(255, 35, 5)}仅供俄语版本使用！{#reset()}此模块将高亮天赋与祝福名称。",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-BR"] = "",
		-- es = "",
	},


--[+Main+]--
	bleed_colour = {
		en = " Bleed",
		fr = " Saignement",
		ru = " Кровотечение",
		["zh-tw"] = " 流血",
		["zh-cn"] = " 流血",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-BR"] = "",
		-- es = "",
	},
	brittleness_colour = {
		en = " Brittleness",
		fr = " Fragilité",
		ru = " Хрупкость",
		["zh-tw"] = " 脆弱",
		["zh-cn"] = " 脆弱",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-BR"] = "",
		-- es = "",
	},
	burn_colour = {
		en = " Burn",
		fr = " Brûlure",
		ru = " Горение",
		["zh-tw"] = " 燃燒",
		["zh-cn"] = " 燃烧",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-BR"] = "",
		-- es = "",
	},
	cleave_colour = {
		en = " Cleave",
		fr = " Transpercement",
		ru = " Рассечение",
		["zh-tw"] = " 順劈目標",
		["zh-cn"] = " 劈裂",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-BR"] = "",
		-- es = "",
	},
	coherency_colour = {
		en = " Coherency",
		-- fr = "",
		ru = " Сплочённость",
		["zh-tw"] = " 協同",
		["zh-cn"] = " 连携",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-BR"] = "",
		-- es = "",
	},
	combat_ability_colour = {
		en = " Combat Ability",
		fr = " Capacité de combat",
		ru = " Боевая способность",
		["zh-tw"] = " 戰鬥能力",
		["zh-cn"] = " 能力",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-BR"] = "",
		-- es = "",
	},
	corruption_colour = {
		en = " Corruption",
		fr = " Corruption",
		ru = " Порча",
		["zh-tw"] = " 腐敗",
		["zh-cn"] = " 腐化",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-BR"] = "",
		-- es = "",
	},
	crit_colour = {
		en = " Crit",
		fr = " Critique",
		ru = " Криты",
		["zh-tw"] = " 暴擊",
		["zh-cn"] = " 暴击",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-BR"] = "",
		-- es = "",
	},
	damage_colour = {
		en = " Damage",
		fr = " Dégât",
		ru = " Урон",
		["zh-tw"] = " 傷害",
		["zh-cn"] = " 伤害",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-BR"] = "",
		-- es = "",
	},
	electrocuted_colour = {
		en = " Electrocuted",
		fr = " Eclair",
		ru = " Поражение током",
		["zh-tw"] = " 電擊",
		["zh-cn"] = " 电击",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-BR"] = "",
		-- es = "",
	},
	finesse_colour = {
		en = " Finesse",
		fr = " Finesse",
		ru = " Точность",
		["zh-tw"] = " 技巧",
		["zh-cn"] = " 灵巧",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-BR"] = "",
		-- es = "",
	},
	health_colour = {
		en = " Health / Wound",
		fr = " Santé / Blessure",
		ru = " Здоровье / Рана",
		["zh-tw"] = " 生命 / 傷痕",
		["zh-cn"] = " 生命值 / 伤口",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-BR"] = "",
		-- es = "",
	},
	hit_mass_colour = {
		en = " Hit Mass",
		fr = " Coup en masse",
		ru = " Ударная масса",
		["zh-tw"] = " 順劈目標",
		["zh-cn"] = " 打击质量",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-BR"] = "",
		-- es = "",
	},
	impact_colour = {
		en = " Impact",
		fr = " Impact",
		ru = " Выведение из равновесия",
		["zh-tw"] = " 衝擊",
		["zh-cn"] = " 冲击",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-BR"] = "",
		-- es = "",
	},
	peril_colour = {
		en = " Peril",
		fr = " Péril",
		ru = " Опасность",
		["zh-tw"] = " 反噬",
		["zh-cn"] = " 危机值",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-BR"] = "",
		-- es = "",
	},
	power_colour = {
		en = " Power",
		fr = " Puissance",
		ru = " Сила",
		["zh-tw"] = " 威力",
		["zh-cn"] = " 强度",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-BR"] = "",
		-- es = "",
	},
	rending_colour = {
		en = " Rending",
		fr = " Déchirure",
		ru = " Пробитие брони",
		["zh-tw"] = " 撕裂",
		["zh-cn"] = " 撕裂",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-BR"] = "",
		-- es = "",
	},
	soulblaze_colour = {
		en = " Soulblaze",
		fr = " Embrasement d'âme",
		ru = " Горение души",
		["zh-tw"] = " 靈魂之火",
		["zh-cn"] = " 灵魂之火",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-BR"] = "",
		-- es = "",
	},
	stagger_colour = {
		en = " Stagger",
		fr = " Vacillement",
		ru = " Ошеломление",
		["zh-tw"] = " 踉蹌",
		["zh-cn"] = " 踉跄",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-BR"] = "",
		-- es = "",
	},
	stamina_colour = {
		en = " Stamina",
		fr = " Endurance",
		ru = " Выносливость",
		["zh-tw"] = " 耐力",
		["zh-cn"] = " 耐力",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-BR"] = "",
		-- es = "",
	},
	toughness_colour = {
		en = " Toughness",
		fr = " Robustesse",
		ru = " Стойкость",
		["zh-tw"] = " 韌性",
		["zh-cn"] = " 韧性",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-BR"] = "",
		-- es = "",
	},
	weakspot_colour = {
		en = " Weak Spot",
		fr = " Coup sur point faible",
		ru = " Уязвимые места",
		["zh-tw"] = " 弱點",
		["zh-cn"] = " 弱点",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-BR"] = "",
		-- es = "",
	},

--[+PSYKER+]--
	class_psyker_colour = {
		en = " Psyker",
		-- fr = "",
		ru = " Псайкер",
		["zh-tw"] = " 靈能者",
		["zh-cn"] = " 灵能者",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-BR"] = "",
		-- es = "",
	},
	precision_colour = {
		en = "	 Precision",
		fr = " Precision",
		ru = "	 Точность",
		["zh-tw"] = " 精準",
		["zh-cn"] = " 精准",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-BR"] = "",
		-- es = "",
	},

--[+OGRYN+]--
	class_ogryn_colour = {
		en = " Ogryn",
		-- fr = "",
		ru = " Огрин",
		["zh-tw"] = " 歐格林",
		["zh-cn"] = " 欧格林",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-BR"] = "",
		-- es = "",
	},
	fnp_colour = {
		en = "	 Feel No Pain",
		fr = " Adieu la douleur",
		ru = "	 Неболит",
		["zh-tw"] = " 麻木",
		["zh-cn"] = " 不痛不痒",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-BR"] = "",
		-- es = "",
	},
	luckyb_colour = {
		en = "	 Lucky bullet",
		fr = " Balles chanceuses",
		ru = "	 Счастливая пуля",
		["zh-tw"] = " 幸運子彈",
		["zh-cn"] = " 幸运子弹",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-BR"] = "",
		-- es = "",
	},
	trample_colour = {
		en = "	 Trample",
		fr = " Piétinement",
		ru = "	 Топот",
		["zh-tw"] = " 衝鋒",
		["zh-cn"] = " 践踏",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-BR"] = "",
		-- es = "",
	},

--[+ZEALOT+]--
	class_zealot_colour = {
		en = " Zealot",
		-- fr = "",
		ru = " Изувер",
		["zh-tw"] = " 狂信徒",
		["zh-cn"] = " 狂信徒",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-BR"] = "",
		-- es = "",
	},
	fury_colour = {
		en = "	 Fury",
		fr = " Piété embrasée",
		ru = "	 Ярость",
		["zh-tw"] = " 狂怒",
		["zh-cn"] = " 怒火",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-BR"] = "",
		-- es = "",
	},
	momentum_colour = {
		en = "	 Momentum",
		fr = " Jugement inexorable",
		ru = "	 Моментум",
		["zh-tw"] = " 勢能",
		["zh-cn"] = " 动量",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-BR"] = "",
		-- es = "",
	},
	stealth_colour = {
		en = "	 Stealth",
		fr = " Furtivité",
		ru = "	 Скрытность",
		["zh-tw"] = " 隱形",
		["zh-cn"] = " 潜行",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-BR"] = "",
		-- es = "",
	},

--[+VETERAN+]--
	class_veteran_colour = {
		en = " Veteran",
		-- fr = "",
		ru = " Ветеран",
		["zh-tw"] = " 老兵",
		["zh-cn"] = " 老兵",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-BR"] = "",
		-- es = "",
	},
	focus_colour = {
		en = "	 Focus",
		fr = " Focalisation",
		ru = "	 Концентрация",
		["zh-tw"] = " 專注",
		["zh-cn"] = " 专注",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-BR"] = "",
		-- es = "",
	},
	focust_colour = {
		en = "	 Focus Target",
		fr = " Ciblage",
		ru = "	 Важная цель",
		["zh-tw"] = " 專注目標",
		["zh-cn"] = " 聚焦目标",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-BR"] = "",
		-- es = "",
	},
	meleespec_colour = {
		en = "	 Melee Specialist",
		fr = " Spcécialiste en mêlée",
		ru = "	 Специалист-рукопашник",
		["zh-tw"] = " 近戰專家",
		["zh-cn"] = " 近战专家",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-BR"] = "",
		-- es = "",
	},
	rangedspec_colour = {
		en = "	 Ranged Specialist",
		fr = " Spcécialiste à distance",
		ru = "	 Специалист-стрелок",
		["zh-tw"] = " 遠程專家",
		["zh-cn"] = " 远程专家",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-BR"] = "",
		-- es = "",
	},

--[+ARBITRATOR+]--
	class_arbites_colour = {
		en = " Arbitrator",
		-- fr = "",
		ru = " Арбитратор",
		-- ["zh-tw"] = "",
		-- ["zh-cn"] = "",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-BR"] = "",
		-- es = "",
	},
	-- meleejust_colour = {
		-- en = "	Melee Justice",
		-- fr = "",
		-- ru = "	Судья-рукопашник",
		-- ["zh-tw"] = "",
		-- ["zh-cn"] = "",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-BR"] = "",
		-- es = "",
	-- },
	-- rangedjust_colour = {
		-- en = "	Ranged Justice",
		-- fr = "",
		-- ru = "	Судья-стрелок",
		-- ["zh-tw"] = "",
		-- ["zh-cn"] = "",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-BR"] = "",
		-- es = "",
	-- },

--[+Misc+]--
	talents_colour = {
		en = " Talents",
		fr = " Talents",
		ru = " Таланты",
		["zh-tw"] = " 天賦",
		["zh-cn"] = " 天赋",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-BR"] = "",
		-- es = "",
	},
	talents_penances_colour = {
		en = " Talents - Penances",
		-- fr = " Talents",
		ru = " Таланты - Искупления",
		["zh-tw"] = " 天賦 - 苦修",
		["zh-cn"] = " 天赋 - 苦修",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-BR"] = "",
		-- es = "",
	},
	numbers_colour = {
		en = " Numbers",
		fr = " Nombres",
		ru = " Числа",
		["zh-tw"] = " 數字",
		["zh-cn"] = " 数字",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-BR"] = "",
		-- es = "",
	},
	variables_colour = {
		en = " Variables",
		fr = " Variables",
		ru = " Переменные",
		["zh-tw"] = " 變數",
		["zh-cn"] = " 变量",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-BR"] = "",
		-- es = "",
	},
	note_colour = {
		en = " Note",
		fr = " Annotation",
		ru = " Примечания",
		["zh-tw"] = " 註釋",
		["zh-cn"] = " 注释",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-BR"] = "",
		-- es = "",
	},
	warning_colour = {
		en = " Warning",
		fr = " Alerte",
		ru = " Предупреждения",
		["zh-tw"] = " 警告",
		["zh-cn"] = " 警告",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-BR"] = "",
		-- es = "",
	},

	--[+Difficulties+]--
	-- sedition_colour = {
		-- en = "Sedition",
		-- fr = "",
		-- ru = "Мятеж",
		-- ["zh-tw"] = "暴動",
		-- ["zh-cn"] = "煽动",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-BR"] = "",
		-- es = "",
	-- },
	uprising_colour = {
		en = "Uprising",
		-- fr = "",
		ru = "Восстание",
		["zh-tw"] = "起義",
		["zh-cn"] = "起义",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-BR"] = "",
		-- es = "",
	},
	malice_colour = {
		en = "Malice",
		-- fr = "",
		ru = "Злоба",
		["zh-tw"] = "惡毒",
		["zh-cn"] = "憎恶",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-BR"] = "",
		-- es = "",
	},
	heresy_colour = {
		en = "Heresy",
		-- fr = "",
		ru = "Ересь",
		["zh-tw"] = "異端",
		["zh-cn"] = "异端",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-BR"] = "",
		-- es = "",
	},
	damnation_colour = {
		en = "Damnation",
		-- fr = "",
		ru = "Проклятие",
		["zh-tw"] = "詛咒",
		["zh-cn"] = "诅咒",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-BR"] = "",
		-- es = "",
	},
	auric_colour = {
		en = "Auric",
		-- fr = "",
		ru = "Золото",
		-- ["zh-tw"] = "",
		-- ["zh-cn"] = "",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-BR"] = "",
		-- es = "",
	},
}

-- INITIALIZATION
-- Add color picker localizations for all groups
for _, group_name in ipairs(LOCALIZATION_GROUPS) do
	add_localisation_entry(localizations, group_name)
end

-- Add color names localizations
add_color_localizations(localizations)

return localizations
